### ISSUE TITLE
cant share screen

### ISSUE THREAD

**Issue by talarari** [maxogden/screencat#59]
getting this error where the shareable link is supposed to be.
Error! getaddrinfo ENOTFOUND catlobby.maxogden.com catlobby.maxogden.com:80

**Comment by talarari** [comment]
ok, browsed the code a bit and i understand the lobby server is not working, so i ran my own cat-lobby on localhost:5005 .
now i dont get the error but there's no text generated in the share code textbox.

does anyone have this working ? would love to run it to get the feel of it. thanks!

**Comment by talarari** [comment]
ok made it run locally, answering myself for documentation

problems i encountered:
* hosted lobby is not available, run your own lobby locally and change the code to go to localhost lobb
* the address in the code that proxies rtcConfig url for cors purposes doesnt work, changed to crossorigin.me
* you need to bundle the web viewer yourself with browserify and serve it over http , i added a bundle npm script to generate the bundle and a  web npm script to server remote.html on express.

the updated code is forked here: https://github.com/talarari/screencat.

to run it locally, run 3 terminals:
* npm  run lobby  - to start your lobby server
* npm start - to start the screencat electron app
* npm run web -to start the webviewer

**Comment by dackom** [comment]
I have used your fork, also managed to make it run locally...

Do you have any idea why cat-lobby server is returning errors 404 when its running on some other machine?

**Comment by roy2651** [comment]
hey,man:
I have used your fork, and run lobby locally,but it doesn't work 
I see lobby server locally user https?
and when I ask the url http://localhost:5005/v1/:roomname/pings  
this url not work !

**Comment by roy2651** [comment]
@dackom I aslo meet this error
have u solve this error

**Comment by dackom** [comment]
No... I gave up on this...

**Comment by timypcr** [comment]
Just give @talarari fork a try after running into issues with the original screencat repo (mostly related to catlobby.maxogden.com being down)  peer.js also references https://instant.io/rtcConfig which is no longer available, does anyone have a copy of rtcConfig used for screencat? 

Thanks

**Comment by roy2651** [comment]
@timypcr u can try this url "https://instant.io/_rtcConfig" this is get iceserver

**Comment by timypcr** [comment]
does anything need to be modify with in the screencat code to get this RTCconfig working other than replacing the urls in peer.js?

Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: 韩加华 <notifications@github.com> Date: 2/2/18  2:32 AM  (GMT-05:00) To: maxogden/screencat <screencat@noreply.github.com> Cc: timypcr <tim@ypcr.com>, Mention <mention@noreply.github.com> Subject: Re: [maxogden/screencat] cant share screen (#59) 
@timypcr u can try this url "https://instant.io/_rtcConfig" this is get iceserver

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/maxogden/screencat","title":"maxogden/screencat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/maxogden/screencat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@roy2651 in #59: @timypcr u can try this url \"https://instant.io/_rtcConfig\" this is get iceserver"}],"action":{"name":"View Issue","url":"https://github.com/maxogden/screencat/issues/59#issuecomment-362508368"}}}

**Comment by roy2651** [comment]
@timypcr first you modefiy catlobby server you can git clone https://github.com/maxogden/cat-lobby  work this repo in your localmachine ,modefiy remoteConfigUrl as https://instant.io/_rtcConfig in peer.js
